---
title: "Česká rozpočtová data"
output:
  html_document:
    toc: false
---

```{r setup, echo = F, message=F, include=F, eval = T}
Sys.setlocale("LC_ALL", "cs_CZ.UTF-8")

knitr::opts_chunk$set(include = F, warning = F, message = F)

library(tidyverse)
library(rvest)
library(lubridate)
library(showtext)

showtext_auto()
```

```{r}
sysfonts::font_add_google(family = "Roboto Condensed", "Roboto Condensed")
sysfonts::font_add_google(family = "Roboto", "Roboto")
```


```{r}
theme_schola <- function(gridlines = c("y", "x", "both", "scatter"),
                         base_size = 11,
                         family = "Roboto Condensed", title_family = "Roboto",
                         margin_side = 6,
                         margin_bottom = 6,
                         plot.title.position = "plot",
                         axis.title = ggplot2::element_blank(),
                         multiplot = FALSE,
                         ...) {
  tonecol <- "#f6f0e8"
  grd <- match.arg(gridlines)
  grid_col <- if(grd == "scatter" | multiplot) "white" else "grey92"
  bg_col <- if(grd == "scatter" | multiplot) tonecol else "white"
  element_gridline <- ggplot2::element_line(colour = grid_col, size = 0.3)
  thm <- ggplot2::theme_minimal(base_size = base_size, base_family = family) +
    ggplot2::theme(plot.title.position = plot.title.position,
                   plot.title = ggplot2::element_text(face = "bold",
                                                      size = base_size * 1.2,
                                                      family = title_family),
                   panel.grid.minor = ggplot2::element_blank(),
                   panel.grid.major.x = if(grd != "y")
                     element_gridline else ggplot2::element_blank(),
                   panel.grid.major.y = if(grd != "x")
                     element_gridline else ggplot2::element_blank(),
                   # axis.line = ggplot2::element_line(),
                   panel.background = ggplot2::element_rect(fill = bg_col,
                                                            colour = NA),
                   axis.title = axis.title,
                   strip.text.x = ggplot2::element_text(hjust = 0),
                   plot.margin = ggplot2::unit(c(10, margin_side,
                                                 margin_bottom, margin_side),
                                               units = "pt"))
  if(multiplot) thm <- thm +
    ggplot2::theme(strip.background = ggplot2::element_rect(fill = tonecol,
                                                            colour = NA))

  thm <- thm +
    ggplot2::theme(...)

  return(thm)
}
```


```{r get data}
dan_vynosy0 <- read_html("https://www.financnisprava.cz/cs/dane/kraje-a-obce/danove-prijmy-kraju-a-obci/prubeh-celostatniho-inkasa-sdilenych-dani-3735") %>% 
  html_table(fill = T, dec = ",")

dan_vynosy <- dan_vynosy0[[2]][,1:8] %>%
  # filter(str_detect(.[,1], "2018")) %>% # is this tbl for 2018? If, not, change index above
  set_names(dan_vynosy0[[2]][2,1:8]) %>% 
  slice(3:n()) %>% 
  pivot_longer(-DATUM) %>%
  mutate(value = str_remove_all(value, " ") %>% 
           str_replace(",", ".") %>% 
           as.numeric(value),
         name = str_replace_all(name, " \n ", " "))

dan_vynosy_all <- bind_rows(dan_vynosy0)

munge_year <- function(df) {
  dff <- df[,1:min(ncol(df), 8)]
  dfff <- set_names(dff, dff[2,])
  dfff %>% 
    slice(3:n()) %>% 
    pivot_longer(-DATUM) %>%
    mutate(value = str_remove_all(value, " ") %>% 
             str_replace(",", ".") %>% 
             as.numeric(value),
           name = str_replace_all(name, " \n ", " "))
}

all <- map_dfr(dan_vynosy0, munge_year) %>% 
  mutate(datum = str_remove(DATUM, "inkaso k "),
         datum_parsed = lubridate::dmy(datum),
         rok = lubridate::year(datum_parsed),
         mesic = lubridate::month(datum_parsed),
         den = lubridate::day(datum_parsed),
         denvroce = lubridate::yday(datum_parsed),
         nazev = str_squish(name),
         grp = paste(rok, nazev)) %>% 
  filter(nazev != "NA") %>% 
  mutate(date_aligned = make_date("2000", mesic, den))

latest <- max(all$datum_parsed, na.rm = T) %>% format("%d. %B %Y")
```

## Výběr daní {.tabset}

### Časové řady

```{r include=T}
ggplot(all %>% 
         # filter(nazev == "DPH") %>%
         filter(!str_detect(nazev, "hazard|technick|LOTER")) %>%
         filter(TRUE), 
       aes(date_aligned, value/1e9, colour = rok, group = grp)) +
  geom_line(aes(group = rok)) +
  gghighlight::gghighlight(calculate_per_facet = T, rok == 2020, use_group_by = T) +
  facet_wrap(~ nazev) + 
  theme_schola("scatter", multiplot = T, plot.caption.position = "plot") + 
  scale_color_viridis_c(labels = scales::label_number(accuracy = 1, big.mark = "")) +
  scale_x_date(labels = scales::label_date(format = "%m"), date_breaks = "months", 
               expand = expansion(c(0.05, 0))) +
  labs(x = "den v roce", title = "Výběr daní podle dat Finanční správy",
       subtitle = str_glue("mld. Kč, poslední údaj z {latest}. Rok 2020 zvýrazněn"),
       caption = "Zdroj: https://www.financnisprava.cz/cs/dane/kraje-a-obce/danove-prijmy-kraju-a-obci/prubeh-celostatniho-inkasa-sdilenych-dani-3735")
```

### Meziroční srovnání

```{r}
all %>% 
  group_by(rok, mesic, nazev) %>% 
  mutate(is_middle = between(den, 10, 20)) %>% 
  summarise(has_middle = any(is_middle)) %>% 
  filter(!has_middle)
```

```{r}
all %>% 
  group_by(rok, mesic, nazev) %>% 
  mutate(is_end = between(den, 25, 31)) %>% 
  summarise(has_end = any(is_end)) %>% 
  group_by(rok, has_end) %>% 
  count()
```



```{r}
all_diffs <- all %>% 
  filter(nazev %in% c("DPH", "DPFO závislá činnost", "DPPO")) %>% 
  mutate(is_end = between(den, 25, 31),
         is_middle = between(den, 10, 20)) %>% 
  filter(is_middle | is_end) %>% 
  mutate(month_part = ifelse(is_middle, "middle", "end")) %>% 
  group_by(mesic, month_part, nazev) %>%
  arrange(nazev, mesic, rok) %>% 
  mutate(narust = value/lag(value) - 1)

hist(all_diffs$narust)
```

```{r, include=T}
library(scales)
# https://gist.github.com/mikmart/bfbf62839fbdd162b4b88e6d43e0c858

c_trans <- function(a, b, breaks = b$breaks, format = b$format) {
  a <- scales::as.trans(a)
  b <- scales::as.trans(b)

  name <- paste(a$name, b$name, sep = "-")

  trans <- function(x) a$trans(b$trans(x))
  inv <- function(x) b$inverse(a$inverse(x))

  scales::trans_new(name, trans, inv, breaks, format = format)
}

rev_date <- c_trans("reverse", "date")

all_diffs %>% 
  ggplot(aes(date_aligned, narust)) +
  geom_hline(yintercept = 0) +
  geom_point(alpha = .6, colour = "red", size = 2) +
  coord_flip() +
  scale_x_continuous(trans = rev_date, labels = label_date("%b"), n.breaks = 12) +
  scale_y_continuous(limits = c(-1, 1), labels = label_percent(suffix = " %")) +
  gghighlight::gghighlight(rok == 2020, unhighlighted_params = list(alpha = .3)) +
  facet_wrap(~ nazev) + theme_schola("scatter", multiplot = T) +
  labs(title = "Meziroční změna výnosu vybraných daní podle období",
       subtitle = "rok 2000 zvýrazněn; extrémní hodnoty vynechány.")
```



### Nejnovější dostupné datové exporty Monitoru státní pokladny

```{r, include=T}
library(jsonlite)
library(httr)
library(dplyr)
library(tidyr)


td <- GET("https://monitor.statnipokladna.cz/api/transakcni-data?aktivni=true",
          accept_json()) %>%
  content(as = "text") %>%
  fromJSON()

xx <- td %>%
  unnest(dataExtracts, .name_repair = "universal")

xx %>%
  group_by(titleCS) %>%
  filter(!deleted, year == max(year)) %>%
  filter(month == max(month)) %>%
  select(titleCS, year, month, filenamePeriod)
```


Naposledy aktualizováno `r format(lubridate::now(tzone = "CET"), "%d. %B %Y %H:%M %Z")`.
